version: "3"

services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: jao89

  redis:
    image: redis:4.0-alpine
    command: redis-server
    ports: 
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  app:
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - ".:/onebittwitter"
      - "app-gems:/app-gems"

volumes:
  redis:
  postgres:
  app-gems: