default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgresql

development:
  <<: *default
  adapter: postgresql
  database: OneBitTwitter_development

test:
  <<: *default
  database: OneBitTwitter_test

production:
  <<: *default
  database: OneBitTwitter_production
  username: OneBitTwitter
  password: <%= ENV['ONEBITTWITTER_DATABASE_PASSWORD'] %>
